name: Deploy PHP para Kinghost (Estratégia Dividida)
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
 
      - name: Deploy Core Files (PHP, Config)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: ./www/administrativo/
          dangerous-clean-slate: false
          log-level: verbose
          timeout: 60000  # 60 segundos (limite do servidor)
          exclude: |
            .git/
            .git/**
            .github/
            .github/**
            .gitignore
            .DS_Store
            README.md
            LICENSE.txt
            node_modules/
            node_modules/**
            .vscode/
            .vscode/**
            logs/
            logs/**
            vendor/
            vendor/**
            bootstrap-5.3.3-dist/
            bootstrap-5.3.3-dist/**
            DataTables/
            DataTables/**
            startbootstrap-sb-admin-gh-pages/
            startbootstrap-sb-admin-gh-pages/**
            app/adms/Views/**
            public/adms/image/**
            public/adms/uploads/**
            public/adms/css/**
            public/adms/js/**
            public/adms/jquery/**
            public/adms/DataTables/**
 
      - name: Deploy Views (Templates)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./app/adms/Views/
          server-dir: ./www/administrativo/app/adms/Views/
          dangerous-clean-slate: false
          log-level: verbose
          timeout: 60000
          exclude: |
            **/.DS_Store
            **/*.log
 
      - name: Deploy Public Assets
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./public/
          server-dir: ./www/administrativo/public/
          dangerous-clean-slate: false
          log-level: verbose
          timeout: 60000
          exclude: |
            **/.DS_Store
            **/*.log